name: Build Artifacts

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or commit to build'
        required: false
        default: 'main'

permissions:
  contents: read

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-mingw-w64

      - name: Build binaries
        run: |
          mkdir -p dist
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o dist/frictionless-launcher-linux-amd64 .
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -o dist/frictionless-launcher-windows-amd64.exe .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-windows-binaries
          path: dist/
          retention-days: 7

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir -p dist
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o dist/frictionless-launcher-darwin-amd64 .
          CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -o dist/frictionless-launcher-darwin-arm64 .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: dist/
          retention-days: 7